version: "3.9"
services:
  analyzer:
    build:
      context: ./task_analyzer
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: juanes
      POSTGRES_PASSWORD: 12345678
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: juanes
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: